Update build-script.template

diff --git a/templates/build-script.template b/templates/build-script.template
--- a/templates/build-script.template
+++ b/templates/build-script.template
@@ -10,17 +10,35 @@
 # See:		GIT URL
 #
 # Usage:	./build-PKGNAME.sh
-#
-#-------------------------------------------------------------------------------
+# Opts:		[--testing]
+#		Modifys build script to denote this is a test package build.
+# -------------------------------------------------------------------------------
+
+#################################################
+# Set variables
+#################################################
 
 arg1="$1"
 scriptdir=$(pwd)
 time_start=$(date +%s)
 time_stamp_start=(`date +"%T"`)
 
+# repo destination vars (use only local hosts!)
+USER="mikeyd"
+HOST="archboxmtd"
+
+if [[ "$arg1" == "--testing" ]]; then
+
+	REPO_FOLDER="/home/mikeyd/packaging/SteamOS-Tools/incoming_testing"
+	
+else
+
+	REPO_FOLDER="/home/mikeyd/packaging/SteamOS-Tools/incoming"
+	
+fi
 # upstream vars
-git_url="GITURL"
-rel_target="TARGET_BRANCH_OR_RELEASE"
+git_url="GIT_URL"
+branch="BRANCH"
 
 # package vars
 date_long=$(date +"%a, %d %b %Y %H:%M:%S %z")
@@ -28,12 +46,13 @@ date_short=$(date +%Y%m%d)
 pkgname="PKGNAME"
 pkgver="VERSION"
 pkgrev="1"
+upstream_rev="1"
 pkgsuffix="git+bsos${pkgrev}"
 dist_rel="brewmaster"
 uploader="SteamOS-Tools Signing Key <mdeguzis@gmail.com>"
 maintainer="ProfessorKaos64"
 
-# set build_dir
+# set build_dirs
 build_dir="$HOME/build-${pkgname}-temp"
 git_dir="${build_dir}/${pkgname}"
 
@@ -43,7 +62,7 @@ install_prereqs()
 	echo -e "==> Installing prerequisites for building...\n"
 	sleep 2s
 	# install basic build packages
-	sudo apt-get -y --force-yes install autoconf automake build-essential pkg-config bc
+	sudo apt-get install -y --force-yes build-essential pkg-config bc
 
 }
 
@@ -51,68 +70,67 @@ main()
 {
 
 	# create build_dir
-	if [[ -d "$build_dir" ]]; then
+	if [[ -d "${build_dir}" ]]; then
 
-		sudo rm -rf "$build_dir"
-		mkdir -p "$build_dir"
+		sudo rm -rf "${build_dir}"
+		mkdir -p "${build_dir}"
 
 	else
 
-		mkdir -p "$build_dir"
+		mkdir -p "${build_dir}"
 
 	fi
 
 	# enter build dir
-	cd "$build_dir" || exit
+	cd "${build_dir}" || exit
 
 	# install prereqs for build
 	install_prereqs
 
 	# Clone upstream source code and branch
+	# NOTE! - If you wish to source versions or commits automatically into variables here,
+	# 	  such as commits, of upstream tags, see docs/pkg-versioning.md
 
 	echo -e "\n==> Obtaining upstream source code\n"
 
-	# clone
-	git clone -b "$rel_target" "$git_url" "$git_dir"
+	# clone and checkout latest commit
+	git clone -b "${branch}" "${git_url}" "${git_dir}"
 	
-	# (optional) remove .git folder to save space on build
-	rm -f "$git_dir/.git"
-
+	# add debian files
+	cp -r "${scriptdir}/debian" "${git_dir}"
+	
+	# Remove files that will conflict with what deb helper and debian/* is doing
+	rm -f "${git_dir}/Makefile"
+	
 	#################################################
-	# Build platform
+	# Build package
 	#################################################
 
 	echo -e "\n==> Creating original tarball\n"
 	sleep 2s
 
-	# create the tarball from latest tarball creation script
-	# use latest revision designated at the top of this script
-
 	# create source tarball
-	tar -cvzf "${pkgname}_${pkgver}.orig.tar.gz" "${pkgname}"
+	cd "${build_dir}" || exit
+	tar -cvzf "${pkgname}_${pkgver}.${pkgsuffix}.orig.tar.gz" "${pkgname}"
 
 	# enter source dir
-	cd "${pkgname}"
-
-	commits_full=$(git log --pretty=format:"  * %cd %h %s")
+	cd "${git_dir}"
 
 	# Create basic changelog format
 	# This addons build cannot have a revision
 	cat <<-EOF> changelog.in
-	$pkgname (${pkgver}+${pkgsuffix}) $dist_rel; urgency=low
+	$pkgname (${pkgver}.${pkgsuffix}) $dist_rel; urgency=low
 
-	  * Packaged deb for SteamOS-Tools
+	  * <CHANGE LOG ITEM>
 	  * See: packages.libregeek.org
-	  * Upstream authors and source: $git_url
-	  * Now includes support for the Lutris Kodi Addon
-	  * For addon information, see: https://github.com/RobLoach/script.lutris
+	  * Upstream authors and source: ${git_url}
 
 	 -- $uploader  $date_long
 
 	EOF
-	
-	# Perform a little trickery to update existing changelog from upstream
-	# If no changelog upstream exists, create a basic changelog file instead.
+
+	# Perform a little trickery to update existing changelog or create
+	# basic file
 	cat 'changelog.in' | cat - debian/changelog > temp && mv temp debian/changelog
 
 	# open debian/changelog and update
@@ -120,8 +138,9 @@ main()
 	sleep 3s
 	nano debian/changelog
 
-	# cleanup old changelog
-	rm -f changelog.in
+ 	# cleanup old files
+ 	rm -f changelog.in
+ 	rm -f debian/changelog.in
 
 	#################################################
 	# Build Debian package
@@ -130,42 +149,44 @@ main()
 	echo -e "\n==> Building Debian package ${pkgname} from source\n"
 	sleep 2s
 
-	#  build
-	dpkg-buildpackage -rfakeroot -us -uc
-	
+	debuild
+
 	#################################################
 	# Cleanup
 	#################################################
-	
+
 	# clean up dirs
-	
+
 	# note time ended
 	time_end=$(date +%s)
 	time_stamp_end=(`date +"%T"`)
 	runtime=$(echo "scale=2; ($time_end-$time_start) / 60 " | bc)
-	
+
 	# output finish
 	echo -e "\nTime started: ${time_stamp_start}"
 	echo -e "Time started: ${time_stamp_end}"
 	echo -e "Total Runtime (minutes): $runtime\n"
 
-	
+
 	# assign value to build folder for exit warning below
 	build_folder=$(ls -l | grep "^d" | cut -d ' ' -f12)
-	
+
 	# back out of build temp to script dir if called from git clone
 	if [[ "$scriptdir" != "" ]]; then
 		cd "$scriptdir" || exit
 	else
 		cd "$HOME" || exit
 	fi
-	
+
 	# inform user of packages
-	echo -e "\n############################################################"
-	echo -e "If package was built without errors you will see it below."
-	echo -e "If you don't, please check build dependcy errors listed above."
-	echo -e "############################################################\n"
-	
+	cat<<- EOF
+	#################################################################
+	If package was built without errors you will see it below.
+	If you don't, please check build dependency errors listed above.
+	#################################################################
+
+	EOF
+
 	echo -e "Showing contents of: ${build_dir}: \n"
 	ls "${build_dir}" | grep -E *${pkgver}*
 
@@ -176,13 +197,18 @@ main()
 
 	if [[ "$transfer_choice" == "y" ]]; then
 
-		# cut files
 		if [[ -d "${build_dir}" ]]; then
-			scp ${build_dir}/*${pkgver}* mikeyd@archboxmtd:/home/mikeyd/packaging/SteamOS-Tools/incoming
-			
+
+			# copy files to remote server
+			rsync -arv --exclude-from=$HOME/.config/SteamOS-Tools/repo-exclude.txt ${build_dir}/*${pkgver}* ${USER}@${HOST}:${REPO_FOLDER}
+
 			# Only move the old changelog if transfer occurs to keep final changelog 
-			# out of the picture until a confirmed build is made. Remove if upstream has their own.
 			cp "${git_dir}/debian/changelog" "${scriptdir}/debian"
+			
+			# If using a fork instead with debiain/ upstream
+			cd "${git_dir}" && git add debian/changelog && git commit -m "update changelog" && git push origin "${branch}"
+			cd "${scriptdir}"
+
 		fi
 
 	elif [[ "$transfer_choice" == "n" ]]; then
